package se.unlogic.standardutils.dao;

import java.lang.reflect.Field;
import java.lang.reflect.Method;

import se.unlogic.standardutils.populators.QueryParameterPopulator;

public interface Column<BeanType,ColumnType> {

	public abstract Field getBeanField();

	public abstract Class<?> getParamType();

	public Object getParamValue(Object param);

	public Object getBeanValue(BeanType bean);

	public abstract Method getQueryMethod();

	public abstract String getColumnName();

	public abstract boolean isAutoGenerated();

	public abstract QueryParameterPopulator<?> getQueryParameterPopulator();

}